# Project-wide Gradle settings.
# For more details on Gradle settings, see https://developer.android.com/studio/build
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX package
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R classes
android.nonTransitiveRClass=true
